# azure-pipelines.yml
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

stages:
- stage: PolicyCheck
  displayName: 'SGNL Policy Check'
  jobs:
  - job: CheckAccess
    displayName: 'Check SGNL Access Policy'
    steps:
    - script: |
        # Install curl and jq for API calls
        sudo apt-get update
        sudo apt-get install -y curl jq
      displayName: 'Install dependencies'

    - script: |
        # Call SGNL Access API
        RESPONSE=$(curl -s -X POST \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer $(SGNL_TOKEN)" \
          -d '{
            "principal": {
              "id": "$(Build.RequestedFor)"
            },
            "queries": [
              {
                "action": "deploy",
                "assetId": "$(Build.Repository.Name)"
              }
            ]
          }' \
          https://access.sgnlapis.cloud/access/v2/evaluations)
        
        echo "SGNL Response: $RESPONSE"
        
        # Extract decision
        DECISION=$(echo $RESPONSE | jq -r '.decisions[0].decision')
        REASON=$(echo $RESPONSE | jq -r '.decisions[0].reason // "No reason provided"')
        
        echo "Decision: $DECISION"
        echo "Reason: $REASON"
        
        # Set pipeline variables
        echo "##vso[task.setvariable;variable=SGNL_DECISION;isOutput=true]$DECISION"
        echo "##vso[task.setvariable;variable=SGNL_REASON;isOutput=true]$REASON"
        
        # Fail if access denied
        if [ "$DECISION" != "Allow" ]; then
          echo "##vso[task.logissue type=error]Access denied by SGNL policy: $REASON"
          exit 1
        fi
      name: sgnlCheck
      displayName: 'SGNL Policy Check'
      env:
        SGNL_TOKEN: $(SGNL_TOKEN)
